version: "3.9"

services:
  web-dev:
    container_name: fsw-111-nextjs-dev
    image: node:22-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - HOSTNAME=0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules

  web:
    container_name: fsw-111-nextjs
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
